package test.com.album.model;

public interface AlbumDB_Oracle {

	String DRIVER_NAME = "oracle.jdbc.OracleDriver";
	String URL = "jdbc:oracle:thin:@localhost:1521:xe";
	String USER = "GOLFMATE";
	String PASSWORD = "admin1234";
	
	String SQL_ALBUM_INSERT = "INSERT INTO ALBUM (ALBUM_ID,CLUB_ID,TITLE,FNAME,WDATE,WRITER) VALUES(SEQ_BOARD.nextval,?,?,?,SYSDATE,?)";
	String SQL_ALBUM_UPDATE = "UPDATE ALBUM SET TITLE = ?, FNAME = ? , WDATE = SYSDATE WHERE ALBUM_ID = ?";
	String SQL_ALBUM_DELETE = "DELETE FROM ALBUM WHERE ALBUM_ID = ?";
	String SQL_ALBUM_SELECT_ALL_DESC = "SELECT * FROM ALBUM WHERE CLUB_ID = ? ORDER BY WDATE DESC";
	String SQL_ALBUM_SELECT_ALL_ASC = "SELECT * FROM ALBUM WHERE CLUB_ID = ? ORDER BY WDATE ASC";
	String SQL_ALBUM_SEARCHlIST_TITLE = "SELECT * FROM ALBUM WHERE CLUB_ID = ? AND UPPER(TITLE) LIKE UPPER(?) ORDER BY WDATE DESC";
	String SQL_ALBUM_SEARCHlIST_WRITER = "SELECT * FROM ALBUM WHERE CLUB_ID = ? AND UPPER(WRITER) LIKE UPPER(?) ORDER BY WDATE DESC";
	
}
